######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 23 13:20:24 2013
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../../src

# Input
SOURCES += empty_string.cpp ../../../src/encryptedstring.cpp ../../../src/securedstring.cpp ../../../src/crypto/bfproxy.cpp ../../../src/crypto/sha1.cpp ../../../src/crypto/blowfish.cpp ../../../src/pwsafe/Util.cpp ../../../src/pwsafe/PW_BlowFish.cpp ../../../src/pwsafe/PW_sha1.cpp
