######################################################################
# Automatically generated by qmake (1.07a) Wed Jul 28 21:51:33 2004
######################################################################

TEMPLATE = app
DEPENDPATH += ../../test ../../src ../../src ../../src ../../src ../../src
INCLUDEPATH += . ../../src ../../uuid-1.0.0
LIBS += ../../uuid-1.0.0/.libs/libuuid.a
LIBS += $$system(cppunit-config --libs)
CONFIG += debug

UI_DIR = .ui
MOC_DIR = .moc
OBJECTS_DIR = .obj

# Input
HEADERS += myutiltest.hpp ../../src/safe.hpp
SOURCES += myutiltest.cpp \
           ../main.cpp \
           ../../src/myutil.cpp \
           ../../src/safe.cpp \
           ../../src/encryptedstring.cpp \
           ../../src/securedstring.cpp \
           ../../src/uuid.cpp \
           ../../src/smartptr.cpp \
           ../../src/pwsafe/BlowFish.cpp \
           ../../src/safeserializer.cpp \
           ../../src/serializers.cpp \
           ../../src/pwsafe/Util.cpp \
           ../../src/pwsafe/sha1.cpp \
           ../../src/plaintextlizer.cpp
