######################################################################
# Automatically generated by qmake (1.07a) Thu Aug 19 18:11:30 2004
######################################################################

TEMPLATE = app
DEPENDPATH += ../../src ../../src
INCLUDEPATH += . ../../uuid-1.0.0 ../../src
LIBS += ../../uuid-1.0.0/.libs/libuuid.a

# Input
HEADERS += ../../src/uuid.hpp ../../src/pwsafe/Util.h
SOURCES += test.cpp ../../src/uuid.cpp ../../src/pwsafe/Util.cpp ../../src/pwsafe/BlowFish.cpp ../../src/pwsafe/sha1.cpp
