######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 23 13:20:24 2013
######################################################################

QT += testlib qt3support
CONFIG += uic3
TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += . ../../src

# Input
RESOURCES += ../../resources.qrc

FORMS3 += ../../src/passphrasedlg.ui
SOURCES += test_passphrasedlg.cpp

