######################################################################
# Automatically generated by qmake (1.07a) Wed Jun 15 02:17:02 2005
######################################################################

TEMPLATE = app
CONFIG += debug
DEPENDPATH += ../../src \
              ../../src \
              ../../src \
              ../../src \
              ../../src/pwsafe \
              ../../src/pwsafe \
              ../../src/pwsafe
INCLUDEPATH += . ../../src ../../src/pwsafe ../../uuid-1.0.0
LIBS    += ../../uuid-1.0.0/.libs/libuuid.a

# Input
HEADERS += ../../src/safe.hpp ../../src/serializers.hpp
SOURCES += safetest.cpp \
           ../../src/safe.cpp \
           ../../src/serializers.cpp \
           ../../src/pwsafe/PW_BlowFish.cpp \
           ../../src/pwsafe/PW_sha1.cpp \
           ../../src/pwsafe/Util.cpp \
           ../../src/securedstring.cpp \
           ../../src/encryptedstring.cpp \
           ../../src/uuid.cpp \
           ../../src/safeserializer.cpp \
           ../../src/myutil.cpp \
           ../../src/smartptr.cpp \
           ../../src/crypto/sha1.cpp \
           ../../src/crypto/bfproxy.cpp \
           ../../src/crypto/blowfish.cpp \
           ../../src/plaintextlizer.cpp \
           ../../src/xmlserializer.cpp
