######################################################################
# Automatically generated by qmake (1.07a) Sun Jul 25 14:21:53 2004
######################################################################

TEMPLATE = app
CONFIG += debug
DEPENDPATH += ../../src \
              ../../src/pwsafe \
	      ../../uuid-1.0.0
INCLUDEPATH += . ../../src ../../src/pwsafe ../../uuid-1.0.0
LIBS    += ../../uuid-1.0.0/.libs/libuuid.a
LIBS	+= $$system(cppunit-config --libs)
#DEFINES += DEBUG

unix {
  UI_DIR = .ui
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}

# Input
HEADERS += ../../src/safe.hpp \
           ../../src/xmlserializer.hpp \
           ../../src/uuid.hpp \
           ../../src/securedstring.hpp \
           ../../src/encryptedstring.hpp \
           ../../src/pwsafe/BlowFish.h \
	   safetest.hpp
SOURCES += safetest.cpp \
           ../../src/safe.cpp \
           ../../src/uuid.cpp \
           ../../src/securedstring.cpp \
           ../../src/encryptedstring.cpp \
           ../../src/pwsafe/BlowFish.cpp \
           ../../src/myutil.cpp \
           ../../src/smartptr.cpp \
           ../../src/pwsafe/Util.cpp \
           ../../src/safeserializer.cpp \
           ../../src/pwsafe/sha1.cpp \
	   ../../src/xmlserializer.cpp
