######################################################################
# Automatically generated by qmake (1.07a) Fri Jul 30 04:34:54 2004
######################################################################

TEMPLATE = app
DEPENDPATH += ../../src ../../src
INCLUDEPATH += . ../../src ../../uuid-1.0.0
LIBS += ../../uuid-1.0.0/.libs/libuuid.a $$system(cppunit-config --libs)

UI_DIR = .ui
MOC_DIR = .moc
OBJECTS_DIR = .obj

# Input
HEADERS += xmlserializertest.hpp ../../src/safe.hpp
SOURCES += xmlserializertest.cpp \
	   ../main.cpp \
           ../../src/safe.cpp \
           ../../src/xmlserializer.cpp \
           ../../src/uuid.cpp \
           ../../src/securedstring.cpp \
           ../../src/encryptedstring.cpp \
           ../../src/smartptr.cpp \
           ../../src/pwsafe/BlowFish.cpp \
           ../../src/myutil.cpp \
           ../../src/safeserializer.cpp \
           ../../src/serializers.cpp \
           ../../src/pwsafe/Util.cpp \
           ../../src/pwsafe/sha1.cpp \
           ../../src/plaintextlizer.cpp
