######################################################################
# Automatically generated by qmake (1.07a) Thu Jul 8 09:07:54 2004
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += dndproto.cpp
HEADERS += dndproto.hpp
